/* Generated By:JavaCC: Do not edit this line. Eg4DefaultVisitor.java Version 6.0_1 */
public class Eg4DefaultVisitor implements Eg4Visitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStart node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAdd node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMult node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMyOtherID node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTInteger node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=4f921e4b345fdf382d6ed73366f7ee44 (do not edit this line) */
