/* Generated By:JavaCC: Do not edit this line. Eg4TreeConstants.java Version 6.0_1 */
public interface Eg4TreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTMULT = 3;
  public int JJTMYOTHERID = 4;
  public int JJTINTEGER = 5;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Add",
    "Mult",
    "MyOtherID",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=43a09614176abab0878b1047db1fd1d5 (do not edit this line) */
