/* Generated By:JavaCC: Do not edit this line. Eg4Visitor.java Version 6.0_1 */
public interface Eg4Visitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTMult node, Object data);
  public Object visit(ASTMyOtherID node, Object data);
  public Object visit(ASTInteger node, Object data);
}
/* JavaCC - OriginalChecksum=5085a0cdfc761a6e19b3b1cf37dee840 (do not edit this line) */
